# Generated by Django 3.0.5 on 2020-09-10 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_location_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='selected',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymessage', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_chat', to='service.Task')),
            ],
        ),
    ]
