# Generated by Django 3.0.5 on 2020-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200917_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
